import React from 'react'
import styles from '../../styles/Home.module.css'
import Image from 'next/image'
import Head from 'next/head'
import Link from "next/link"
import logo from "../../public/images/fresh_movie_logo.png"

const Layout = (props) => {
  return (
    <div>
    <Head>
        <title>{props.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <div className={styles.logo}>
          <Link href={"/"}><a><Image src={logo} width={120} height={70}/></a></Link>

        </div>

        <nav className={styles.nav}>
         <ul>
            <li><Link href={"/"}><a>Home</a></Link></li>
            <li><Link href={"/movies"}><a>Movies</a></Link></li>
            <li><Link href={"/about-us"}><a>About Us</a></Link></li>
         </ul>
         </nav>
      </header>
        <main >{props.children}</main>
        <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Layout